inventario/urls.py
# -*- coding: utf-8 -*-
# vim:ts=4:expandtab:ai
# $Id: urls.py 20 2025-11-27 21:10:24Z vic@gssi.es $

from django.urls import path

app_name = 'inventario'

from .views import TipoList
from .views import TipoDetail
from .views import TipoCreate
from .views import TipoUpdate
from .views import TipoDelete
from .views import UbicacionList
from .views import UbicacionDetail
from .views import UbicacionCreate
from .views import UbicacionUpdate
from .views import UbicacionDelete
from .views import ObjetoList
from .views import ObjetoDetail
from .views import ObjetoCreate
from .views import ObjetoUpdate
from .views import ObjetoDelete

urlpatterns = [
    path('tipo', TipoList.as_view(), name='tipo-list'),
    path('tipo/add', TipoCreate.as_view(), name='tipo-create'),
    path('tipo/<int:pk>', TipoDetail.as_view(), name='tipo-detail'),
    path('tipo/<int:pk>/edit', TipoUpdate.as_view(), name='tipo-update'),
    path('tipo/<int:pk>/del', TipoDelete.as_view(), name='tipo-delete'),
    path('ubicacion', UbicacionList.as_view(), name='ubicacion-list'),
    path('ubicacion/add', UbicacionCreate.as_view(), name='ubicacion-create'),
    path('ubicacion/<int:pk>', UbicacionDetail.as_view(), name='ubicacion-detail'),
    path('ubicacion/<int:pk>/edit', UbicacionUpdate.as_view(), name='ubicacion-update'),
    path('ubicacion/<int:pk>/del', UbicacionDelete.as_view(), name='ubicacion-delete'),
    path('objeto', ObjetoList.as_view(), name='objeto-list'),
    path('objeto/add', ObjetoCreate.as_view(), name='objeto-create'),
    path('objeto/<int:pk>', ObjetoDetail.as_view(), name='objeto-detail'),
    path('objeto/<int:pk>/edit', ObjetoUpdate.as_view(), name='objeto-update'),
    path('objeto/<int:pk>/del', ObjetoDelete.as_view(), name='objeto-delete'),
    path('', ObjetoCreate.as_view(), name='objeto-create'),
]

inventario/templates/inventario/base.html
<!DOCTYPE html>
<!-- vim:ts=2:expandtab:ai
$Id: base.html 13 2025-07-21 21:45:56Z vic@gssi.es $
-->
{% load static %}
{% load admin_urls %}
<html>
  <head>
  <title>{% block title %}{% endblock %}</title>
    <style>
      html {
        /* This prevents the page from shifting when a modal is opened e.g. search */
        overflow-y: auto;   
      }
      IMG.banner {
        margin-top: 10px;
        margin-bottom: 10px;
        display: block;
        margin-left: auto;
        margin-right: auto;
        float: left;
      }
      DIV.banner {
        margin-top: 10px;
      }
      #main {
        display: table;
        border-collapse: collapse;
        width: 100%;
      }
      #header {
        display: table-row;
        width: 100%;
      }
      #footer {
        display: table-row;
        width: 100%;
      }
      #middle {
        display: table-row;
        width: 100%;
      }
      #content {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 95%;
      }
      @media print {
        a[href]:after {
            display: none;
        }     
      }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    {% block extrahead %}{% endblock %}
  </head>
  <body>
    <div id="main">
      <div id="header">
        <img class="banner" src="{% static "logo.jpeg" %}" width="100px">
        <div class="banner">
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Gestión</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#lanavbar"
                    aria-controls="lanavbar"
                    aria-expanded="false" aria-label="Navegación">
              <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse" id="lanavbar">
            <ul class="navbar-nav mr-auto">
 
              <li class="nav-item">
                <a class="nav-link" href="{% url "inventario:tipo-list" %}">Tipo</a>
              </li>
    
              <li class="nav-item">
                <a class="nav-link" href="{% url "inventario:objeto-list" %}">Objeto</a>
              </li>
     
            </ul>
          </div>
        </nav>
      </div>
      <div id="middle">
        <div id="content">
          {% if messages %}
          <div>
          {% for message in messages %}
            <div class="alert alert-block alert-{{message.tags}}">
              <button type="button" class="close" data-dismiss="alert">
                &times;
              </button>
              {{ message|safe|linebreaks }}
            </div>
          {% endfor %}
          </div>
          {% endif %}
        {% block content %}{% endblock %}
        </div>
      </div>
      <div id="footer">
        <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
        {% block footer %}{% endblock %}
      </div>
    </div>
  </body>
</html>

inventario/templates/inventario/objeto_confirm_delete.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<table class="table table-striped">
  <thead>
   <tr><th colspan=2><h1>Objeto</h1></th></tr>
  </thead>
  <body>
    <tr>
      <td>Tipo</td>
      <td>{{ object.tipo }}</td>
    </tr>
    <tr>
      <td>Etiqueta</td>
      <td>{{ object.etiqueta }}</td>
    </tr>
    <tr>
      <td>Nombre</td>
      <td>{{ object.nombre }}</td>
    </tr>
    <tr>
      <td>Imagen</td>
      <td>{{ object.imagen }}</td>
    </tr>
    <tr>
      <td>Descripcion</td>
      <td>{{ object.descripcion }}</td>
    </tr>
  </body>
</table>
<form method="post">
   {% csrf_token %}
   <input class="btn btn-danger" type="submit" value="Confirmar borrado">
 </form>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: objeto_confirm_delete.html 13 2025-07-21 21:45:56Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/objeto_detail.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<table class="table table-striped">
  <thead>
   <tr><th colspan=2><h1>Objeto</h1></th></tr>
  </thead>
  <body>
    <tr>
      <td>Tipo</td>
      <td>{{ object.tipo }}</td>
    </tr>
    <tr>
      <td>Etiqueta</td>
      <td>{{ object.etiqueta }}</td>
    </tr>
    <tr>
      <td>Nombre</td>
      <td>{{ object.nombre }}</td>
    </tr>
    <tr>
      <td>Imagen</td>
      <td>{{ object.imagen }}</td>
    </tr>
    <tr>
      <td>Descripcion</td>
      <td>{{ object.descripcion }}</td>
    </tr>
  </body>
</table>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: objeto_detail.html 13 2025-07-21 21:45:56Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/objeto_form.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<form method="post" enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.as_p }}
   <input class="btn btn-success" type="submit" value="Guardar">
 </form>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: objeto_form.html 24 2025-12-01 00:23:26Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/objeto_list.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<table class="table table-hover">
  <thead>
   <tr>
     <th colspan="2"><h1>Objeto</h1></th>
     <th>
       <a href="{% url "inventario:objeto-create"  %}" class="btn btn-outline-primary">Añadir</a></h1>
     </th>
   </tr>
  </thead>
  <tbody>
{% for o in object_list %}
    <tr>
       <td>
         <a href="{% url "inventario:objeto-detail" o.pk %}" class="btn btn-outline-primary btn-lg btn-block"> {{o}}</a>
       </td>
       <td>
     <a href="{% url "inventario:objeto-update" o.pk %}" class="btn btn-primary">Editar</a>
       </td>
       <td>
     <a href="{% url "inventario:objeto-delete" o.pk %}" class="btn btn-danger">Borrar</a>
       </td>
       </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: objeto_list.html 13 2025-07-21 21:45:56Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/tipo_comfirm_delete.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<table class="table table-striped">
  <thead>
   <tr><th colspan=2><h1>Tipo</h1></th></tr>
  </thead>
  <body>
    <tr>
      <td>Nombre</td>
      <td>{{ object.nombre }}</td>
    </tr>
    <tr>
      <td>Descripcion</td>
      <td>{{ object.descripcion }}</td>
    </tr>
  </body>
</table>
<form method="post">
   {% csrf_token %}
   <input class="btn btn-danger" type="submit" value="Confirmar borrado">
 </form>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: tipo_confirm_delete.html 13 2025-07-21 21:45:56Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/tipo_detail.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<table class="table table-striped">
  <thead>
   <tr><th colspan=2><h1>Tipo</h1></th></tr>
  </thead>
  <body>
    <tr>
      <td>Nombre</td>
      <td>{{ object.nombre }}</td>
    </tr>
    <tr>
      <td>Descripcion</td>
      <td>{{ object.descripcion }}</td>
    </tr>
  </body>
</table>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: tipo_detail.html 13 2025-07-21 21:45:56Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/tipo_form.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input class="btn btn-success" type="submit" value="Guardar">
 </form>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: tipo_form.html 13 2025-07-21 21:45:56Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/tipo_list.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<table class="table table-hover">
  <thead>
   <tr>
     <th colspan="2"><h1>Tipo</h1></th>
     <th>
       <a href="{% url "inventario:tipo-create"  %}" class="btn btn-outline-primary">Añadir</a></h1>
     </th>
   </tr>
  </thead>
  <tbody>
{% for o in object_list %}
    <tr>
       <td>
         <a href="{% url "inventario:tipo-detail" o.pk %}" class="btn btn-outline-primary btn-lg btn-block"> {{o}}</a>
       </td>
       <td>
     <a href="{% url "inventario:tipo-update" o.pk %}" class="btn btn-primary">Editar</a>
       </td>
       <td>
     <a href="{% url "inventario:tipo-delete" o.pk %}" class="btn btn-danger">Borrar</a>
       </td>
       </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: tipo_list.html 13 2025-07-21 21:45:56Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/ubicacion_comfirm_delete.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<table class="table table-striped">
  <thead>
   <tr><th colspan=2><h1>Tipo</h1></th></tr>
  </thead>
  <body>
    <tr>
      <td>Nombre</td>
      <td>{{ object.nombre }}</td>
    </tr>
    <tr>
      <td>Descripcion</td>
      <td>{{ object.descripcion }}</td>
    </tr>
  </body>
</table>
<form method="post">
   {% csrf_token %}
   <input class="btn btn-danger" type="submit" value="Confirmar borrado">
 </form>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: ubicacion_confirm_delete.html 20 2025-11-27 21:10:24Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/ubicacion_detail.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<table class="table table-striped">
  <thead>
   <tr><th colspan=2><h1>Tipo</h1></th></tr>
  </thead>
  <body>
    <tr>
      <td>Nombre</td>
      <td>{{ object.nombre }}</td>
    </tr>
    <tr>
      <td>Descripcion</td>
      <td>{{ object.descripcion }}</td>
    </tr>
  </body>
</table>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: ubicacion_detail.html 20 2025-11-27 21:10:24Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/ubicacion_form.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input class="btn btn-success" type="submit" value="Guardar">
 </form>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: ubicacion_form.html 20 2025-11-27 21:10:24Z vic@gssi.es $
{% endcomment %}

inventario/templates/inventario/ubicacion_list.html
{% extends "inventario/base.html" %}
{% load static %}


{% block content %}
<table class="table table-hover">
  <thead>
   <tr>
     <th colspan="2"><h1>Tipo</h1></th>
     <th>
       <a href="{% url "inventario:tipo-create"  %}" class="btn btn-outline-primary">Añadir</a></h1>
     </th>
   </tr>
  </thead>
  <tbody>
{% for o in object_list %}
    <tr>
       <td>
         <a href="{% url "inventario:tipo-detail" o.pk %}" class="btn btn-outline-primary btn-lg btn-block"> {{o}}</a>
       </td>
       <td>
     <a href="{% url "inventario:tipo-update" o.pk %}" class="btn btn-primary">Editar</a>
       </td>
       <td>
     <a href="{% url "inventario:tipo-delete" o.pk %}" class="btn btn-danger">Borrar</a>
       </td>
       </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}


{% comment %}
vim:ts=2:expandtab:ai
$Id: ubicacion_list.html 20 2025-11-27 21:10:24Z vic@gssi.es $
{% endcomment %}